//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaystationGameList
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GameListDatabaseEntities : DbContext
    {
        public GameListDatabaseEntities()
            : base("name=GameListDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Developer> Developers { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<GameDevMap> GameDevMaps { get; set; }
        public virtual DbSet<GameGenreMap> GameGenreMaps { get; set; }
        public virtual DbSet<GamePlatformMap> GamePlatformMaps { get; set; }
        public virtual DbSet<GamePublisherMap> GamePublisherMaps { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<Platform> Platforms { get; set; }
        public virtual DbSet<Publisher> Publishers { get; set; }
    }
}
