//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaystationGameList
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameDevMap
    {
        public int ID { get; set; }
        public Nullable<int> GameID { get; set; }
        public Nullable<int> DevID { get; set; }
    
        public virtual Developer Developer { get; set; }
        public virtual Game Game { get; set; }
    }
}
